apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: storyverse
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: storyverse/api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: UNIVERSE_SERVICE_URL
          value: "http://universe-management:8080"
        - name: CHARACTER_SERVICE_URL
          value: "http://character-database:8080"
        - name: TEXT_GENERATION_URL
          value: "http://text-generation:8080"
        - name: IMAGE_GENERATION_URL
          value: "http://image-generation:8080"
        - name: AUDIO_GENERATION_URL
          value: "http://audio-narration:8080"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: storyverse
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: storyverse
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.storyverse.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
