apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: storyverse
type: Opaque
data:
  uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvc3Rvcnl2ZXJzZQ== # mongodb://mongodb:27017/storyverse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: storyverse
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: storyverse
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
