apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: storyverse
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /health {
            return 200 'healthy';
            add_header Content-Type text/plain;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>StoryVerse Demo</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
        h1 {
            color: #4285f4;
        }
        .container {
            margin-top: 50px;
            text-align: center;
        }
    </style>
    </head>
    <body>
    <div class="container">
        <h1>StoryVerse Demo</h1>
        <p>This is a placeholder for the StoryVerse application.</p>
        <p>This instance is running on EKS with AutoMode enabled.</p>
        <p>The application demonstrates how a complex microservices architecture with varying resource requirements can efficiently scale across availability zones.</p>
        <p><em>Powered by AWS EKS AutoMode</em></p>
    </div>
    </body>
    </html>
